## ---- packages
# Load packages  
library(synthos)
library(ggplot2)
library(dplyr)
library(readr)
library(sf)
library(INLA)
library(patchwork)
library(inlabru)
library(purrr)
library(tidyr)
library(stars)
library(RColorBrewer)
library(lubridate)
library(stringr)
library(FRK) 
library(spacetime)
library(ggvanced)
library(sysfonts)
library(showtext)
library(sp)
library(ggdist)
library(LaCroixColoR)
library(wesanderson)
library(ggpubr)
library(viridis)
